# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'countly-sdk-react-native-bridge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Countly', "20.04"
  # Pods for countly-sdk-react-native-bridge

end